services:
  instantclient:
    build:
      context: .
      dockerfile: docker/instantclient/Dockerfile
      additional_contexts:
        software: ${SOFTWARE_DIR:-./software}
      args:
        OL_VERSION: ${OL_VERSION}
        ORACLE_IC_VERSION: ${ORACLE_IC_VERSION}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_SERVICE: ${DB_SERVICE}
    image: ol8/instantclient/32bit:${ORACLE_IC_VERSION}

  mde:
    build:
      context: .
      dockerfile: docker/mde/Dockerfile
      additional_contexts:
        software: ${SOFTWARE_DIR:-./software}
      args:
        INSTANTCLIENT_IMAGE: ol8/instantclient/32bit:${ORACLE_IC_VERSION}
        SIEBEL_VERSION: ${SIEBEL_VERSION}
        SIEBEL_UID: ${SIEBEL_UID}
        SIEBEL_GID: ${SIEBEL_GID}
        PKI_PWD: ${PKI_PWD}
        PKI_DOMAIN: ${PKI_DOMAIN}
        SES_HTTP_PORT: ${SES_HTTP_PORT:-5090}
        SES_SHUTDOWN_PORT: ${SES_SHUTDOWN_PORT:-5092}
        SES_REDIRECT_PORT: ${SES_REDIRECT_PORT:-5091}
        AI_HTTP_PORT: ${AI_HTTP_PORT:-6090}
        AI_SHUTDOWN_PORT: ${AI_SHUTDOWN_PORT:-6092}
        AI_REDIRECT_PORT: ${AI_REDIRECT_PORT:-6091}
        AI_USERNAME: ${AI_USERNAME:-SADMIN}
        AI_USER_PWD: ${AI_USER_PWD}
        GW_TLS_PORT: ${GW_TLS_PORT:-2320}
        SIEBEL_ENTERPRISE: ${SIEBEL_ENTERPRISE:-dev01}
        MDE_HOSTNAME: ${MDE_HOSTNAME:-dev01mde01}
    image: ol8/siebel/mde-base:${SIEBEL_VERSION}np
    container_name: ${MDE_HOSTNAME}
    hostname: ${MDE_HOSTNAME}
    networks:
      siebelnet:
        aliases:
          - ${MDE_HOSTNAME}.${PKI_DOMAIN}
    user: "${SIEBEL_UID}:${SIEBEL_GID}"
    tty: true
    stdin_open: true
    ports:
      - "4443:${AI_REDIRECT_PORT:-6091}"
      - "${GW_REGISTRY_PORT:-2322}:${GW_REGISTRY_PORT:-2322}"
    volumes:
      - ./siebel-volumes/MDE01:/persistent
      - ./siebel-volumes/SFS:/sfs
      - ${DATA_DIR:-./data}/webroot:/siebel/mde/applicationcontainer_external/siebelwebroot
    environment:
      sesServerName: MDE01
    depends_on:
      - oracle19c
    restart: unless-stopped

  test-db:
    image: ol8/instantclient/32bit:${ORACLE_IC_VERSION}
    networks:
      - siebelnet
    environment:
      ORACLE_PWD: ${ORACLE_PWD}
    command: >
      bash -c "echo 'SELECT 1 FROM DUAL;' |
      sqlplus -S sys/${ORACLE_PWD}@//${DB_HOST}:${DB_PORT}/${DB_SERVICE} as sysdba"
    profiles:
      - test

  oracle19c:
    image: container-registry.oracle.com/database/enterprise_ru:latest-19
    container_name: ${DB_HOST}
    hostname: ${DB_HOST}
    networks:
      siebelnet:
        aliases:
          - ${DB_HOST}
    ports:
      - "${DB_PORT}:1521"
      - "5500:5500"
    env_file: .env
    environment:
      ENABLE_ARCHIVELOG: "true"
    volumes:
      - ${ORACLE_DATA_DIR:-./oracle-data}:/opt/oracle/oradata
      - ${DATA_DIR:-./data}/dumps:/opt/oracle/dumps
      - ./init-scripts/setup:/opt/oracle/scripts/setup
    shm_size: '2gb'
    restart: unless-stopped

networks:
  siebelnet:
    name: siebelnet

