services:
  instantclient:
    build:
      context: .
      dockerfile: docker/instantclient/Dockerfile
      args:
        OL_VERSION: ${OL_VERSION}
        ORACLE_IC_VERSION: ${ORACLE_IC_VERSION}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_SERVICE: ${DB_SERVICE}
    image: ol8/instantclient/32bit:${ORACLE_IC_VERSION}

  cgw:
    build:
      context: .
      dockerfile: docker/cgw/Dockerfile
      args:
        INSTANTCLIENT_IMAGE: ol8/instantclient/32bit:${ORACLE_IC_VERSION}
        SIEBEL_VERSION: ${SIEBEL_VERSION}
        PKI_PWD: ${PKI_PWD}
        PKI_DOMAIN: ${PKI_DOMAIN}
        GW_HTTP_PORT: ${GW_HTTP_PORT:-4091}
        GW_SHUTDOWN_PORT: ${GW_SHUTDOWN_PORT:-4092}
        GW_REDIRECT_PORT: ${GW_REDIRECT_PORT:-4090}
    image: ol8/siebel/cgw-base:${SIEBEL_VERSION}np

  ses:
    build:
      context: .
      dockerfile: docker/ses/Dockerfile
      args:
        INSTANTCLIENT_IMAGE: ol8/instantclient/32bit:${ORACLE_IC_VERSION}
        SIEBEL_VERSION: ${SIEBEL_VERSION}
        PKI_PWD: ${PKI_PWD}
        PKI_DOMAIN: ${PKI_DOMAIN}
        SES_HTTP_PORT: ${SES_HTTP_PORT:-5090}
        SES_SHUTDOWN_PORT: ${SES_SHUTDOWN_PORT:-5092}
        SES_REDIRECT_PORT: ${SES_REDIRECT_PORT:-5091}
    image: ol8/siebel/ses-base:${SIEBEL_VERSION}np

  test-db:
    image: ol8/instantclient/32bit:${ORACLE_IC_VERSION}
    networks:
      - siebelnet
    environment:
      ORACLE_PWD: ${ORACLE_PWD}
    command: >
      bash -c "echo 'SELECT 1 FROM DUAL;' |
      sqlplus -S sys/${ORACLE_PWD}@//${DB_HOST}:${DB_PORT}/${DB_SERVICE} as sysdba"
    profiles:
      - test

  oracle19c:
    image: container-registry.oracle.com/database/enterprise_ru:latest-19
    container_name: ${DB_HOST}
    hostname: ${DB_HOST}
    networks:
      siebelnet:
        aliases:
          - ${DB_HOST}
    ports:
      - "${DB_PORT}:1521"
      - "5500:5500"
    env_file: .env
    environment:
      ENABLE_ARCHIVELOG: "true"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./dumps:/opt/oracle/dumps
      - ./init-scripts/setup:/opt/oracle/scripts/setup
    shm_size: '2gb'
    restart: unless-stopped

networks:
  siebelnet:
    name: siebelnet

volumes:
  oracle_data:
