services:
  instantclient:
    build:
      context: ./docker/instantclient
      args:
        OL_VERSION: ${OL_VERSION}
        ORACLE_IC_VERSION: ${ORACLE_IC_VERSION}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_SERVICE: ${DB_SERVICE}
    image: ol8/instantclient/32bit:${ORACLE_IC_VERSION}

  test-db:
    image: ol8/instantclient/32bit:${ORACLE_IC_VERSION}
    networks:
      - siebelnet
    environment:
      ORACLE_PWD: ${ORACLE_PWD}
    command: >
      bash -c "echo 'SELECT 1 FROM DUAL;' |
      sqlplus -S sys/${ORACLE_PWD}@//${DB_HOST}:${DB_PORT}/${DB_SERVICE} as sysdba"
    profiles:
      - test

  oracle19c:
    image: container-registry.oracle.com/database/enterprise_ru:latest-19
    container_name: ${DB_HOST}
    hostname: ${DB_HOST}
    networks:
      siebelnet:
        aliases:
          - ${DB_HOST}
    ports:
      - "${DB_PORT}:1521"
      - "5500:5500"
    env_file: .env
    environment:
      ENABLE_ARCHIVELOG: "true"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./dumps:/opt/oracle/dumps
      - ./init-scripts/setup:/opt/oracle/scripts/setup
    shm_size: '2gb'
    restart: unless-stopped

networks:
  siebelnet:
    name: siebelnet

volumes:
  oracle_data:
